drop table riskofphysicaldamage;
drop table battery;
drop table warning;
drop table environmentsomelowvisibility;
drop table lowbattery;
drop table movingobject;
drop table hasspeedsomefast;
drop table hasaltitudesomelow;
drop table pilotedbysomeinexperienced;
drop table hasaltitudesomehigh;
drop table haspartsomelowbattery;
drop table environmentsomeindoor;
drop table flyingabovesomewater;
drop table haspartsomeemptybattery;
drop table flying;
drop table movingobject;
drop table object;
drop table vv;
drop table status_final;
drop table experienced;
drop table notwaterproofdrone;

drop table status;
drop table emptybattery;
drop table environment;
drop table fast;
drop table flyingabove;
drop table ground;
drop table hasaltitude;
drop table haspart;
drop table hasspeed;
drop table high;
drop table indoor;
drop table inexperienced;
drop table low;
drop table lowbattery;
drop table pilotedby;
drop table water;
drop table drone;

drop type weather;
drop type frame;
drop type ground_water;

drop table drone;
drop table dirtylenses;
drop table goingbackwards;
drop table waterproofdrone;
drop table flyingabove;

drop table p;
drop table p0;
drop table p1;
drop table p2;
drop table p3;
drop table p4;
drop table p5;
drop table p6;
drop table p7;
drop table p8;
drop table p9;
drop table p10;
drop table p11;
drop table p12;
drop table p13;
drop table p14;
drop table p15;
drop table p16;
drop table p17;
drop table p19;
drop table p20;
drop table p21;
drop table p22;
drop table p23;
drop table p24;
drop table p25;
drop table tmp_provsql;

select remove_provenance('goingbackwards');
select remove_provenance('indoor');
select remove_provenance('low');
select remove_provenance('high');
select remove_provenance('dirtylenses');
select remove_provenance('emptybattery');
select remove_provenance('fast');
select remove_provenance('ground');
select remove_provenance('inexperienced');
select remove_provenance('lowbattery');
select remove_provenance('water');
select remove_provenance('waterproofdrone');
select remove_provenance('drone');
